server:
  port: 8081

spring:
  application:
    name: client-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/client_service
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  flyway:
    url: jdbc:postgresql://localhost:15432/client_service
    schemas: client_service
    user: root
    password: root123


