server:
  port: 8080

spring:
  application:
    name: customer-service
  profiles:
    active: prod
  jpa:
    open-in-view: true
management:
  endpoints:
    web:
      exposure:
        include: "health"
