version: '3.1'

services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: customer_service
    ports:
      - 15432:5432
    volumes:
      - vol_postgres:/var/lib/postgresql/data
    networks:
      - net_postgres


  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080
    networks:
      - net_postgres

volumes:
  vol_postgres:

networks:
  net_postgres:
    driver: bridge